version: '3.8'
services:
  api:
    container_name: api
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15.1-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=graphql
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data



volumes:
  db:
    driver: local