version: "3.9"
services:
  api:
    container_name: graphql-api
    build: "."
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dvdrental

    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: